languages = ("Python", "Java", "C++", "JavaScript", "Ruby")
print("Original tuple:", languages)
print("Length of the tuple:", len(languages))
print("First element:", languages[0])
print("Last element:", languages[-1])
print(type(languages))